var data = {
questions: [' What was the last funny video you saw?',
 ' What do you do to get rid of stress?',
 ' What is something you are obsessed with?',
 ' What three words best describe you?',
 ' What would be your perfect weekend?',
 ' What do you think of tattoos? Do you have any?',
 ' What’s your favorite number? Why?',
 ' What’s the most useful thing you own? ',
 ' What’s your favorite way to waste time?',
 ' Do you have any pets? What are their names?',
 ' Where did you go last weekend? What did you do?',
 ' What are you going to do this weekend?',
 ' What is something that is popular now that annoys you?',
 ' What did you do on your last vacation?',
 ' When was the last time you worked incredibly hard?',
 ' Are you very active or do you prefer to just relax in your free time?',
 ' What do you do when you hang out with your friends?',
 ' Who is your oldest friend? Where did you meet them?',
 ' What’s the best / worst thing about your work / school?',
 ' If you had intro music, what song would it be? Why?',
 ' What were you really into when you were a kid?',
 ' If you could have any animal as a pet, what animal would you choose?',
 ' Have you ever saved an animal’s life? How about a person’s life?',
 ' If you opened a business, what kind of business would it be?',
 ' Who is your favorite entertainer (comedian, musician, actor, etc',
 ' Are you a very organized person?',
 ' Have you ever spoken in front of a large group of people? How did it go?',
 ' What is the strangest dream you have ever had?',
 ' What is a controversial opinion you have?',
 ' Who in your life brings you the most joy?',
 ' Who had the biggest impact on the person you have become?',
 ' What is the most annoying habit someone can have?',
 ' Where is the most beautiful place you have been?',
 ' Where do you spend most of your free time / day?',
 ' Who was your best friend in elementary school?',
 ' How often do you stay up past 3 a',
 ' What’s your favorite season? Why?',
 ' Which is more important, a great car or a great house? Why?',
 ' What animal or insect do you wish humans could eradicate?',
 ' Where is the most beautiful place near where you live?',
 ' What do you bring with you everywhere you go?',
 ' How much time do you spend on the internet? What do you usually do?',
 ' What is the most disgusting habit some people have?',
 ' Where and when was the most amazing sunset you have ever seen?',
 ' Which recent news story is the most interesting?',
 ' Where is the worst place you have been stuck for a long time?',
 ' If you had to change your name, what would your new name be?',
 ' What is something that really annoys you but doesn’t bother most people?',
 ' What word or saying from the past do you think should come back?',
 ' How should success be measured? By that measurement, who is the most successful person you know?',
 ' What is your guilty pleasure?',
 ' Was there ever an event in your life that defied explanation?',
 ' If you could learn the answer to one question about your future, what would the question be?',
 ' Has anyone ever saved your life?',
 ' What benefit do you bring to the group when you hang out with friends?',
 ' How often do you curse?',
 ' What trends did you follow when you were younger?',
 ' What do you fear is hiding in the dark?',
 ' What was the best time period of your life? What do you think will be the best time period of your entire life?',
 ' What do you do to improve your mood when you are in a bad mood?',
 ' What is the silliest fear you have?',
 ' What are some things you want to accomplish before you die?',
 ' What is the best room in your house? Why?',
 ' Who is someone who is popular now that you really like? Why do you like them so much?',
 ' Where is the best place to take a date?',
 ' What smell brings back great memories?',
 ' What’s the best pet name you can come up for a specific type of pet? (Like these orange cat names',
 ' How often do you help others? Who do you help? How do you help?',
 ' What are you best at?',
 ' What makes you nervous?',
 ' Who, besides your parents, had the biggest impact on your life?',
 ' What weird or useless talent do you have?',
 ' What are some strange beliefs that some people have?',
 ' Who would be the worst person to be stuck in an elevator with? How about the best person to be stuck in an elevator with?',
 ' What’s the funniest TV series you have seen?',
 ' Which TV show do you want your life to be like?',
 ' If you could bring back one TV show that was cancelled, which one would you bring back?',
 ' How have TV shows changed over the years?',
 ' What’s the best sitcom past or present?',
 ' What’s the best show currently on TV?',
 ' What do you think about game shows? Do you have a favorite one?',
 ' What’s the most underrated or overrated TV show?',
 ' What do you think about reality TV? Why is it so popular?',
 ' Do you like reality TV shows? Why or why not? If so, which ones?',
 ' What will be the future of TV shows?',
 ' What was the best birthday wish or gift you’ve ever received?',
 ' How often do you binge watch shows?',
 ' What cartoons did you watch as a child?',
 ' What is the most overrated movie?',
 ' What’s your favorite genre of movie?',
 ' Which do you prefer? Books or movies?',
 ' What movie scene choked you up the most?',
 ' Do you like documentaries? Why / why not?',
 ' What’s the worst movie you have seen recently?',
 ' What’s the strangest movie you have ever seen?',
 ' Do you like horror movies? Why or why not?',
 ' When was the last time you went to a movie theater?',
 ' What was the last movie you watched? How was it?',
 ' Do movies have the same power as books to change the world?',
 ' Do you prefer to watch movies in the theater or in the comfort of your own home? ',
 ' What was the last book you read?',
 ' What was your favorite book as a child?',
 ' Do you prefer physical books or ebooks?',
 ' What is the longest book you have read?',
 ' What book genres do you like to read?',
 ' Do you prefer fiction or nonfiction books?',
 ' What book has influenced you the most?',
 ' How fast do you read?',
 ' How often do you go to the library?',
 ' What book has had the biggest impact on your life? ',
 ' What book has had the biggest effect on the modern world?',
 ' What was the worst book you had to read for school? How about the best book you had to read for school? ',
 ' Do you think people read more or less books now than 50 years ago?',
 ' Now that indie publishing has become easier, have books gotten better or worse?',
 ' What song always puts you in a good mood?',
 ' What’s the best way to discover new music? ',
 ' What was the last song you listened to?',
 ' What is your favorite movie soundtrack?',
 ' Do you like classical music?',
 ' How has technology changed the music industry? ',
 ' Are there any songs that always bring a tear to your eye?',
 ' What bands or types of music do you listen to when you exercise?',
 ' Which do you prefer, popular music or relatively unknown music?  ',
 ' Do you like going to concerts? Why or why not? What was the last concert you went to?',
 ' Who was the first band or musician you were really into? Do you still like them?',
 ' Records, tapes, CDs, MP3s',
 ' What are the three best apps on your phone?',
 ' What is the most useful app on your phone?',
 ' What apps have changed your life a lot?',
 ' What do app makers do that really annoys you? ',
 ' How many apps do you have on your phone?',
 ' What is the most annoying app you have tried?',
 ' What’s the most addictive mobile game you have played?',
 ' Which app seemed like magic the first time you used it?',
 ' What is the strangest app you have heard of or tried?',
 ' Which app has helped society the most? Which one has hurt society the most?',
 ' An app mysteriously appears on your phone that does something amazing',
 ' How often do you check your phone?',
 ' Do you always have to have the latest phone?',
 ' Do you text more or call more? Why?',
 ' What will phones be like in 10 years? ',
 ' What is the most annoying thing about your phone?',
 ' How do you feel if you accidentally leave your phone at home?',
 ' What do you wish your phone could do? ',
 ' What kind of case do you have for your phone? Why did you choose it?',
 ' What was your first smart phone? How did you feel when you got it? ',
 ' Do you experience phantom vibration? (Feeling your phone vibrate even though it didn’t',
 ' What sports do you like to watch?',
 ' Who are some of your favorite athletes?',
 ' Which sports do you like to play?',
 ' What is the hardest sport to excel at?',
 ' Who are the 3 greatest athletes of all time?',
 ' What do you think the oldest sport still being played is?',
 ' How much time do you spend watching sports in a week?',
 ' Do athletes deserve the high salaries they receive? Why or why not?',
 ' What defines a sport? Is fishing a sport? How about video game tournaments?',
 ' Why do you think sports are common across almost all cultures present and past?',
 ' Do you play sports video games? Which ones? Is playing the video game or sport more fun? Why?',
 ' Which sport is the most exciting to watch? Which is the most boring to watch?',
 ' What restaurant do you eat at most?',
 ' What’s the worst fast food restaurant?',
 ' What is the best restaurant in your area?',
 ' What is the fanciest restaurant you have eaten at?',
 ' What kind of interior do you like a restaurant to have?',
 ' What is the worst restaurant you have ever eaten at?',
 ' If you opened a restaurant, what kind of food would you serve?',
 ' What is the strangest themed restaurant you have heard of?',
 ' Would you eat at a restaurant that was really dirty if the food was amazing?',
 ' What is the most disgusting thing you have heard about that happened at a restaurant?',
 ' What was your favorite restaurant when you were in university? How about when you were a child? ',
 ' Where would you like to travel next?',
 ' What is the longest plane trip you have taken?',
 ' What’s the best way to travel? (Plane, car, train, etc',
 ' Where is the most relaxing place you have been?',
 ' Do you prefer traveling alone or with a group?',
 ' What do you think of tour group packages?',
 ' Do you prefer to go off the beaten path when you travel?',
 ' What was the most over hyped place you’ve traveled to?',
 ' Have you traveled to any different countries? Which ones?',
 ' Where is the most awe inspiring place you have been?',
 ' What’s the best thing about traveling? How about the worst thing?',
 ' What is the worst hotel you have stayed at? How about the best hotel?',
 ' How do you think traveling to a lot of different countries changes a person?',
 ' Talk about some of the interesting people you have met while traveling',
 ' What do you think of stay-cations? (Vacationing and seeing tourist attractions where you live',
 ' Where do you get your recommendations for what to do and where to stay when you travel?',
 ' What is your favorite piece of technology that you own?',
 ' What piece of technology is really frustrating to use?',
 ' What was the best invention of the last 50 years?',
 ' Does technology simplify life or make it more complicated?',
 ' Will technology save the human race or destroy it?',
 ' Which emerging technology are you most excited about?',
 ' What scifi movie or book would you like the future to be like?',
 ' What do you think the next big technological advance will be? ',
 ' What technology from a science fiction movie would you most like to have?',
 ' What problems will technology solve in the next 5 years? What problems will it create?',
 ' What piece of technology would look like magic or a miracle to people in medieval Europe?',
 ' Can you think of any technology that has only made the world worse? How about a piece of technology that has only made the world better?',
 ' What is your favorite shirt?',
 ' Does fashion help society in any way?',
 ' What old trend is coming back these days?',
 ' What is a fashion trend you are really glad went away?',
 ' What is the most comfortable piece of clothing you own?',
 ' What is the most embarrassing piece of clothing you own?',
 ' How do clothes change how the opposite sex views a person?',
 ' Do you care about fashion? What style of clothes do you usually wear?',
 ' If you didn’t care at all what people thought of you, what clothes would you wear?',
 ' What is the best pair of shoes you have ever owned? Why were they so good?',
 ' Who do you think has the biggest impact on fashion trends: actors and actresses, musicians, fashion designers, or consumers?',
 ' What personal goals do you have?',
 ' What are your goals for the next two years?',
 ' How have your goals changed over your life?',
 ' How much do you plan for the future?',
 ' How do you plan to make the world a better place?',
 ' What are some goals you have already achieved?',
 ' What do you hope to achieve in your professional life?',
 ' Have your parents influenced what goals you have?',
 ' Do you usually achieve goals you set? Why or why not?',
 ' What is the best way to stay motivated and complete goals?',
 ' What are some goals you have failed to accomplish?',
 ' What is the craziest, most outrageous thing you want to achieve?',
 ' When do you want to retire? What do you want to do when you retire? ',
 ' Do you prefer summer or winter activities?',
 ' What do you like to do in spring?',
 ' Did your family take seasonal vacations?',
 ' Do you feel like fall and spring are getting shorter?',
 ' Which season are you most active in?',
 ' What’s the most refreshing thing on a hot summer day?',
 ' What’s the best thing to do on a cold winter day?',
 ' Where is the nicest place you have been to in fall?',
 ' What is your favorite thing to eat or drink in winter?',
 ' Is it better to live where there are four seasons or where one season takes up most of the year?',
 ' What is the biggest holiday for your family?',
 ' What is your favorite holiday?',
 ' What holidays have been over commercialized?',
 ' Do you wish there were more or less holidays? Why?',
 ' What do you know about the history of some holidays?',
 ' What kinds of food do you usually eat on your favorite holiday?',
 ' If you had to get rid of a holiday, which would you get rid of? Why?',
 ' Does having a day off for a holiday increase or decrease productivity at work?',
 ' If some of the lesser known holidays were commercialized, what would the commercialization look like?',
 ' If you could make a holiday, what would it be like? What traditions would it have? What would people eat on your holiday?',
 ' Here are some Christmas trivia questions, Halloween trivia questions, and some Thanksgiving trivia questions',
 ' What do you think of online education?',
 ' How can governments make education more efficient?',
 ' What do you think of standardized tests?',
 ' Are bigger or small schools better?',
 ' Is teaching a skill that can be taught?',
 ' What will the future of education be?',
 ' What do you think of homeschooling?',
 ' How has the education you received changed your life?',
 ' How can technology improve education? Can it hurt education?',
 ' What or who has taught you most of the information you use on a regular basis?',
 ' What are some good and bad things about the education system in your country? ',
 ' What is your favorite food?',
 ' What foods do you absolutely hate?',
 ' What do you think of buffets?',
 ' When was the last time you had a food fight?',
 ' What food looks disgusting but tastes delicious? ',
 ' What do you get every time you go grocery shopping?',
 ' If your life was a meal, what would kind of meal would it be?',
 ' What would you want your last meal to be if you were on death row?',
 ' What food do you know you shouldn’t eat but can’t help yourself?',
 ' Do you like spicy food? Why or why not? What is the spiciest thing you have ever eaten?',
 ' Does government have a place in regulating food? To what extent should government regulate food? ',
 ' When people make mistakes about food (especially foreign food) do you feel the need to correct them? (i',
 ' If your mind was an island, what would it look like?',
 ' What flavor of ice cream do you wish existed?',
 ' If you had a personal mascot, what would your mascot be?',
 ' If you were a king / queen, what would your throne look like?',
 ' Time freezes for everyone but you for one day',
 ' You have to relive one day of your life forever',
 ' What does your own personal hell look like? How about your own personal heaven?',
 ' You find a remote that can rewind, fast forward, stop and start time',
 ' If you could call up anyone in the world and have a one hour conversation, who would you call?',
 ' If you were on the run from the police for a crime you didn’t commit, where would you go?',
 ' A portal to another world opens in front of you',
 ''],
 phrasal_verbs: [
 'add up',
 'act up',
 'agree with',
 'aim at',
 'amount to',
 'answer back',
 'arrive on',
 'ask around',
 'ask in',
 'ask over',
 'back into',
 'back off',
 'back out',
 'back up',
 'bail out',
 'barge in',
 'bear in mind',
 'beef up',
 'belt up',
 'be out',
 'be with it',
 'beat up',
 'bend down',
 'bend over',
 'bite into',
 'black out',
 'blast away',
 'blast off',
 'blend in',
 'blow away',
 'blow out',
 'blow up',
 'blow over',
 'boil over',
 'book into',
 'botom out',
 'bounce back',
 'bounce off',
 'branch off',
 'branch out',
 'break away',
 'break down',
 'break in',
 'break loose',
 'break off',
 'break out',
 'break through',
 'brighten up',
 'bring back',
 'bring down',
 'bring in',
 'bring out',
 'bring together',
 'bring up',
 'brush aside',
 'brush off',
 'buckle up',
 'build on',
 'build up',
 'bundle up',
 'burn down',
 'burn out',
 'burst in',
 'burst out',
 'butt in',
 'butt out',
 'button up',
 'buy into',
 'buy out',
 'buy off',
 'buy up',
 'call back',
 'call for',
 'call in',
 'call off',
 'call on',
 'call out',
 'call up',
 'calm down',
 'cancel out',
 'carry off',
 'carry on',
 'carry out',
 'care for',
 'cash in',
 'cast aside',
 'cast out',
 'catch on',
 'catch up',
 'charge in',
 'cheat on',
 'check in',
 'check into',
 'check off',
 'check out',
 'check up',
 'cheer up',
 'chew up',
 'chicken out',
 'chip away',
 'chip in',
 'choke on',
 'choke up',
 'chop off',
 'chop up',
 'clam up',
 'clean up',
 'clean out',
 'clear out',
 'clear up',
 'close down',
 'close in',
 'close off',
 'close up',
 'come across',
 'come along',
 'come apart',
 'come around',
 'come back',
 'come down',
 'come form',
 'come in',
 'come on',
 'come out',
 'come over',
 'come through',
 'come up',
 'cook out',
 'cook up',
 'cool down',
 'cool off',
 'copy down',
 'count on',
 'count out',
 'cover up',
 'crack down',
 'crack up',
 'creep upon',
 'crop up',
 'cross off',
 'cross out',
 'cry out',
 'curl up',
 'cut back',
 'cut down',
 'cut in',
 'cut off',
 'cut out',
 'cut up',
 'dash off',
 'dash out',
 'dawn on',
 'deal with',
 'decide on',
 'depend on',
 'descend from',
 'die down',
 'die for',
 'die out',
 'dig in',
 'dig into',
 'dig out',
 'dine out',
 'dispose of',
 'dive in',
 'divide into',
 'do without',
 'do up',
 'double over',
 'doze of',
 'drag on',
 'drag out',
 'drain out',
 'draw back',
 'draw near',
 'draw out',
 'dress up',
 'dress down',
 'drift off',
 'drift to',
 'drink down',
 'drink to',
 'drink up',
 'drive way',
 'drive down',
 'drive off',
 'drive on',
 'drive through',
 'drive up',
 'drop behind',
 'drop by',
 'drop down',
 'drop in',
 'drop off',
 'drop out',
 'dry out',
 'dry up',
 'duck down',
 'dust off',
 'ease off',
 'ease up',
 'eat away',
 'eat in',
 'eat out',
 'eat up',
 'empty out',
 'end up',
 'enter into',
 'even out',
 'face off',
 'face up',
 'fade away',
 'fade out',
 'fall apart',
 'fafll away',
 'fall behind',
 'fall down',
 'fall for',
 'fall into',
 'fall off',
 'fall out',
 'fall over',
 'fall through',
 'fall upon',
 'feel for',
 'fear for',
 'fend off',
 'fight back',
 'fight down',
 'fight off',
 'figure on',
 'figure out',
 'fill in',
 'fill out',
 'fill up',
 'find out',
 'finish off',
 'finish up',
 'finish with',
 'fire back',
 'fish for',
 'fish out',
 'fit in',
 'fit into',
 'fix up',
 'flare up',
 'flip thorugh',
 'flock together',
 'fly by',
 'fold up',
 'follow through',
 'follow up',
 'fool around',
 'freshen up',
 'frighten away',
 'fuel up',
 'gather around',
 'gather in',
 'gather up',
 'gear up',
 'get about',
 'get away',
 'get away with',
 'get across',
 'get around',
 'get along',
 'get back',
 'get by',
 'get down',
 'get down to',
 'get in',
 'get into',
 'get off',
 'get on',
 'get out',
 'get over',
 'get through',
 'get up',
 'give away',
 'give back',
 'give in',
 'give out',
 'give up',
 'glance through',
 'go about',
 'go after',
 'go against',
 'go ahead',
 'go along',
 'go around',
 'go away',
 'go back',
 'go by',
 'go down',
 'go for',
 'go in',
 'go into',
 'go off',
 'go on',
 'go out',
 'go over',
 'go through',
 'go ounder',
 'go up',
 'go without',
 'grab on',
 'grow into',
 'grow up',
 'hammer at',
 'hammer down',
 'hand back',
 'hand in',
 'hand out',
 'hand over',
 'hang around',
 'hang on',
 'hang out',
 'hang up',
 'head back',
 'hear from',
 'heap up',
 'heat up',
 'help out',
 'hide away',
 'hit back',
 'hit it off',
 'hold back hold back',
 'hold down',
 'hold off',
 'hold on',
 'hold up',
 'hollow out',
 'home in',
 'hook up',
 'hop in',
 'huddle up',
 'hunt down',
 'hunt out',
 'hurry away',
 'hurry back',
 'hurry up',
 'hush up',
 'improve on',
 'insist on',
 'interfere with',
 'intrude on',
 'invest in',
 'invite out',
 'invite over',
 'iron out',
 'join in',
 'join up',
 'jot down',
 'jump in',
 'jump off',
 'keep at',
 'keep away',
 'keep down',
 'keep from',
 'keep off',
 'keep on',
 'keep out',
 'keep to',
 'keep up',
 'kill off',
 'kick off',
 'knock down',
 'knock it off',
 'knock out',
 'knock over',
 'lag behind',
 'lap up',
 'lash out',
 'laught off',
 'launch into',
 'lay away',
 'lay off',
 'lay out',
 'lead to',
 'leak out',
 'lean over',
 'leap for',
 'leave behind',
 'leave on',
 'leave out',
 'let down',
 'let in',
 'let off',
 'let out',
 'let up',
 'level off',
 'level out',
 'lie ahead',
 'lie down',
 'lift off',
 'light up',
 'line up',
 'linger on',
 'link up',
 'listen in',
 'live through',
 'liive up to',
 'live without',
 'liven up',
 'load up',
 'lock out',
 'lock up',
 'log off',
 'log on',
 'log out',
 'look after',
 'look at',
 'look away',
 'look back',
 'look down',
 'look for',
 'look forward to',
 'look into',
 'look on',
 'look out',
 'look through',
 'look up',
 'loosen up',
 'lose out',
 'lounge around',
 'make off',
 'make out',
 'make over',
 'make up',
 'make up for',
 'march on',
 'mark down',
 'mark up',
 'match up',
 'measure up',
 'meet up',
 'melt down',
 'mess about',
 'mess up',
 'miss out',
 'mix in',
 'mix up',
 'mop up',
 'move away',
 'move back',
 'move in',
 'move off',
 'move on',
 'move out',
 'move over',
 'move up',
 'nail down',
 'narrow down',
 'open up',
 'pack up',
 'paint over',
 'pair up',
 'part with',
 'pass around',
 'pass away',
 'pass by',
 'pass on',
 'pass out',
 'pass up',
 'patch up',
 'pay back',
 'pay for',
 'pay off',
 'pay up',
 'peek in',
 'pelt down',
 'pencil in',
 'perk up',
 'pick on',
 'pick out',
 'pick up',
 'piece together',
 'pile up',
 'pin down',
 'pitch in',
 'plan ahead',
 'plan out',
 'play along',
 'play back',
 'play with',
 'plot out',
 'plow through',
 'plug away',
 'plug in',
 'plunge in',
 'point out',
 'polish off',
 'pop in',
 'pop out',
 'pop up',
 'post up',
 'pound away',
 'pour down',
 'press on',
 'print out',
 'proceed against',
 'profit from',
 'provide for',
 'pry into',
 'pull away',
 'pull back',
 'pull down',
 'pull in',
 'pull off',
 'pull ouot',
 'pull over',
 'pull through',
 'pull together',
 'pull up',
 'push around',
 'push on',
 'put aside',
 'put away',
 'put back',
 'put down',
 'put in',
 'put on',
 'put off',
 'put out',
 'put through',
 'put together',
 'put up',
 'put up with',
 'queue up',
 'quiet down',
 'raise up',
 'ram through',
 'ramble on',
 'reach down',
 'reach out',
 'read over',
 'reel under',
 'reel in',
 'refrain from',
 'frelate to',
 'rely on',
 'remind of',
 'report back',
 'resort to',
 'rev up',
 'ride away',
 'ride off',
 'ride on',
 'ride out',
 'ring back',
 'ring up',
 'rinse off',
 'rip off',
 'rip up',
 'rise up',
 'roll down',
 'roll off',
 'roll over',
 'roll up',
 'round off',
 'rub out',
 'rule against',
 'rule in favor',
 'rule out',
 'run after',
 'run away',
 'run down',
 'run for',
 'run into',
 'run off',
 'run on',
 'run out',
 'run over',
 'run through',
 'run up',
 'rush in',
 'rush off',
 'rush out',
 'sail through',
 'save up',
 'scare off',
 'scout around',
 'scrape by',
 'scratch out',
 'screw down',
 'screw up',
 'secure against',
 'see through',
 'sell off',
 'sell out',
 'send away for',
 'send back',
 'send for',
 'send out',
 'set apart',
 'set back',
 'set down',
 'set off',
 'set out',
 'set up',
 'settle down',
 'settle in',
 'sew up',
 'shake up',
 'shape up',
 'shine through',
 'ship off',
 'shoot out',
 'show off',
 'show out',
 'show up',
 'shrivel up',
 'shrugg off',
 'shut down',
 'shut off',
 'shut out',
 'shut up',
 'sign in',
 'sign off',
 'sign on',
 'sign up',
 'single out',
 'sit back',
 'sit down',
 'sit in',
 'sit up',
 'size up',
 'slam down',
 'sleep in',
 'sleep over',
 'sleep through',
 'slim down',
 'slip on',
 'sli out',
 'slip up',
 'slow down',
 'smash down',
 'smash into',
 'smash up',
 'sneak in',
 'sneak out',
 'sneak up',
 'sober up',
 'sort out',
 'speak for',
 'speak out',
 'speak up',
 'speed up',
 'spell out',
 'split off',
 'split up',
 'spread out',
 'stack up',
 'stall off',
 'stamp out',
 'stand around',
 'stand aside',
 'stand back',
 'stand by',
 'stand for',
 'stand in',
 'stand out',
 'stand up',
 'stand up for',
 'start off',
 'start out',
 'start over',
 'start up',
 'stash away',
 'stay behind',
 'stay over',
 'stay up',
 'step aside',
 'step back',
 'step down',
 'step out',
 'step up',
 'stick around',
 'stick down',
 'stick out',
 'stick together',
 'stick with',
 'stir up',
 'stock up',
 'stop by',
 'stop over',
 'stop up',
 'storm in',
 'storm out',
 'straighten out',
 'straighten up',
 'stretch out',
 'strike back',
 'strip off',
 'struggle through',
 'sum up',
 'swallow down',
 'swallow up',
 'swear at',
 'swear by',
 'sweep away',
 'sweep up',
 'swell up',
 'swith off',
 'switch on',
 'switch over',
 'take after',
 'take apart',
 'take away',
 'take back',
 'tacke down',
 'take in',
 'take off',
 'take out',
 'take over',
 'take up',
 'talk back',
 'talk into',
 'taper off',
 'team up',
 'tear down',
 'tear up',
 'tell off',
 'tell on',
 'think back',
 'think over',
 'thrive on',
 'throw away',
 'throw up',
 'tick off',
 'tidy up',
 'tie down',
 'tie in',
 'tie up',
 'tighten up',
 'tip off',
 'tip over',
 'tire out',
 'top up',
 'toss up',
 'touch down',
 'touch up',
 'toughen up',
 'tow away',
 'track down',
 'trigger off',
 'trip up',
 'try on',
 'try out',
 'turn about',
 'turn around',
 'turn back',
 'turn in',
 'turn into',
 'turn off',
 'turn on',
 'turn out',
 'turn over',
 'turn up',
 'use up',
 'veer off',
 'vouch for',
 'wait up',
 'wake up',
 'walk off',
 'walk out',
 'want out',
 'warm up',
 'wash away',
 'wash out',
 'wash up',
 'water down',
 'watch out',
 'wear off',
 'wear out',
 'weigh down',
 'whip up',
 'wind up',
 'wipe off',
 'wipe out',
 'wise up',
 'work away',
 'work on',
 'work out',
 'wrap up',
 'write down',
 'write off',
 'write out',
 'yell out',
 'zero in',
 'zip up',
 'zoom off'],
agree: ["I couldn't agree with you more",
"We're on the same page",
"That's for sure",
'Tell me about it!',
"You're absolutely right",
"That's exactly how I feel",
'I have to side with you on this one',
'No doubt about it',
'You have a point there',
'I was just going to say that',
"Ok that's convincing",
'You took the words right out of my mouth',
"I'd go along with that",
"Actually I think you're right",
'I second that',
'I take your word on it',
'I share your point of view',
'I feel the same way',
'You nailed it on the head'],
disagree: ["I'm afraid I disagree",
'I totally disagree',
'I beg to differ',
"I'd say the exact opposite",
'Not necessarily',
"That's not always true",
"That's not always the case",
"No I'm not so sure about that",
'I see your point but',
"That's one way of looking at it however",
'Well I see things differently',
"I'm not sure I go along with that view",
'I agree up to a point but',
"I wouldn't put it that way myself",
'I find that very difficult to accept',
'There is no way I could agree with that',
'I see what you mean but',
'I still have my doubts',
"That's out of question"]
};